/**
 * Regenerates src/models.generated.ts from models.dev. Only the providers basis
 * ships are kept; provider plugins overlay their own facts (see catalogFor).
 *
 *   nix develop -c bun run --cwd plugins/llm generate-models
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { GeneratedModel } from "../src/models.generated.ts";

const SOURCE = "https://models.dev/api.json";
/** models.dev provider id → basis provider id. `ollama` has no catalog there; it stays an empty placeholder. */
const PROVIDERS: Readonly<Record<string, string>> = { anthropic: "anthropic", openai: "openai", openrouter: "openrouter", ollama: "ollama" };

interface SourceModel {
  readonly id: string;
  readonly name: string;
  readonly reasoning?: boolean;
  readonly tool_call?: boolean;
  readonly modalities?: { readonly output?: readonly string[] };
  readonly limit?: { readonly context?: number; readonly output?: number };
  readonly cost?: { readonly input?: number; readonly output?: number; readonly cache_read?: number; readonly cache_write?: number };
}
type Source = Record<string, { readonly models?: Record<string, SourceModel> }>;

function toModel(provider: string, model: SourceModel): GeneratedModel | undefined {
  // Embedding and image models have no text output and cannot serve a chat request.
  if (model.modalities?.output !== undefined && !model.modalities.output.includes("text")) return undefined;
  const context = model.limit?.context;
  if (context === undefined || context <= 0) return undefined;
  const cost = model.cost;
  return {
    id: `${provider}/${model.id}`,
    provider,
    name: model.name,
    contextWindow: context,
    ...(model.limit?.output === undefined ? {} : { maxOutput: model.limit.output }),
    toolCall: model.tool_call ?? false,
    reasoning: model.reasoning ?? false,
    ...(cost?.input === undefined || cost.output === undefined ? {} : {
      cost: {
        input: cost.input, output: cost.output,
        ...(cost.cache_read === undefined ? {} : { cacheRead: cost.cache_read }),
        ...(cost.cache_write === undefined ? {} : { cacheWrite: cost.cache_write }),
      },
    }),
  };
}

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE} responded ${response.status}`);
const source = (await response.json()) as Source;

const lines: string[] = [];
for (const [sourceId, provider] of Object.entries(PROVIDERS)) {
  const models = Object.values(source[sourceId]?.models ?? {})
    .map((model) => toModel(provider, model))
    .filter((model): model is GeneratedModel => model !== undefined)
    .sort((a, b) => a.id.localeCompare(b.id));
  lines.push(`  ${JSON.stringify(provider)}: [`);
  for (const model of models) lines.push(`    ${JSON.stringify(model)},`);
  lines.push("  ],");
}

const date = new Date().toISOString().slice(0, 10);
const output = `// Generated by scripts/generate-models.ts from ${SOURCE} on ${date}. Do not edit by hand.

/** Field-compatible with the ModelInfo constructor in @basis/contracts. */
export interface GeneratedModel {
  readonly id: string;
  readonly provider: string;
  readonly name: string;
  readonly contextWindow: number;
  readonly maxOutput?: number;
  readonly toolCall: boolean;
  readonly reasoning: boolean;
  readonly cost?: { readonly input: number; readonly output: number; readonly cacheRead?: number; readonly cacheWrite?: number };
}

export const generatedAt = ${JSON.stringify(date)};

export const generated: Readonly<Record<string, readonly GeneratedModel[]>> = {
${lines.join("\n")}
};
`;
const target = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "models.generated.ts");
writeFileSync(target, output);
console.log(`wrote ${target}`);
